---
- name: Install pip packages
  pip:
    name:
      - kubernetes

- name: Install localhost.direct ssl certificates
  copy:
    src: "{{item}}"
    dest: /usr/share/ca-certificates/localhost/
    mode: 0644
  with_items:
  - localhost.direct.crt
  - localhost.direct.key

- name: Transfer argocd server config values file
  template:
    src: argocd-values.yml
    dest: /tmp/argocd-values.yml
    mode: 0644

- name: Install argocd helm chart
  kubernetes.core.helm:
    release_name: argocd
    chart_ref: argo-cd
    chart_repo_url: https://argoproj.github.io/argo-helm
    release_namespace: "{{argocd_namespace}}"
    create_namespace: yes
    wait: yes
    values_files:
      - /tmp/argocd-values.yml
  become_user: "{{admin_user}}"

###################################################################################
# Argo Image Updater
- name: Install argo image updater helm chart
  kubernetes.core.helm:
    release_name: argo
    chart_ref: argocd-image-updater
    chart_repo_url: https://argoproj.github.io/argo-helm
    release_namespace: "{{argocd_namespace}}"
    create_namespace: yes
    wait: yes
  become_user: "{{admin_user}}"

###################################################################################
# Argo Rollouts
- name: Transfer argo rollouts config values file
  template:
    src: rollouts-values.yml
    dest: "/tmp/rollouts-values.yml"
    mode: 0644

- name: Install argo rollouts helm chart
  kubernetes.core.helm:
    release_name: argo-rollouts
    chart_ref: argo-rollouts
    chart_repo_url: https://argoproj.github.io/argo-helm
    release_namespace: "{{argorollouts_namespace}}"
    create_namespace: yes
    wait: yes
    values_files:
      - /tmp/rollouts-values.yml
  become_user: "{{admin_user}}"

- name: Download argo rollouts cli
  ansible.builtin.get_url:
    url: https://github.com/argoproj/argo-rollouts/releases/latest/download/kubectl-argo-rollouts-linux-amd64
    dest: /usr/local/bin/kubectl-argo-rollouts-linux-amd64
    mode: 0755
    validate_certs: no

- name: Download argo-rollouts extension manifest
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/argoproj-labs/rollout-extension/v0.3.0/manifests/install.yaml
    dest: /tmp/argo-rollouts-extension.yml
    mode: 0664
    validate_certs: no

- name: Install argocd-rollout extension
  kubernetes.core.k8s:
    namespace: "{{argocd_namespace}}"
    state: present
    src: /tmp/argo-rollouts-extension.yml
  become_user: "{{admin_user}}"

###################################################################################
# Notification templates and catalog
- name: Download notification templates and catalog
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/notifications_catalog/install.yaml
    dest: /tmp/notifications_catalog.yaml
    mode: '0664'
    validate_certs: no

- name: Install notifications catalog
  kubernetes.core.k8s:
    namespace: "{{argocd_namespace}}"
    state: present
    src: /tmp/notifications_catalog.yaml
  become_user: "{{admin_user}}"

