---
- name: Install python k8s api
  ansible.builtin.apt:
    name:
      - python3-kubernetes

- name: Install localhost.direct ssl certificates
  copy:
    src: "{{item}}"
    dest: /usr/share/ca-certificates/localhost/
    mode: 0644
  with_items:
  - localhost.direct.crt
  - localhost.direct.key

#- name: Transfer argocd server config values file
#  template:
#    src: argocd-values.yml
#    dest: /tmp/argocd-values.yml
#    mode: 0644

- name: Install argocd helm chart
  kubernetes.core.helm:
    release_name: argocd
    chart_ref: argo-cd
    chart_repo_url: https://argoproj.github.io/argo-helm
    release_namespace: "{{argocd_namespace}}"
    create_namespace: yes
    wait: yes
    values_files:
      - /tmp/argocd-values.yml
  become_user: "{{admin_user}}"

- name: Install Argo Rollouts
  ansible.builtin.import_tasks: rollouts.yml
- name : Install ArgoCD Image Updater
  ansible.builtin.import_tasks: imageupdater.yml
- mame: Install Argo Workflows
  ansible.builtin.import_tasks: workflows.yml
#- name: Install kargo
#  ansible.builtin.import_tasks: kargo.yml
#- name: Install notifications
#  ansible.builtin.import_tasks: notifications.yml
