---
- name: Install pip packages
  pip:
    name:
      - kubernetes

- name: Transfer argocd server config values file
  template:
    src: values.yml
    dest: "/tmp/argocd_values.yml"
    mode: 0644

- name: Install argocd helm chart
  kubernetes.core.helm:
    release_name: "{{argocd_app_name}}"
    chart_ref: argo-cd
    chart_repo_url: https://argoproj.github.io/argo-helm
    release_namespace: "{{argocd_namespace}}"
    create_namespace: true
    wait: yes
    values_files:
      - /tmp/argocd_values.yml
  become_user: "{{admin_user}}"

###################################################################################
# Export config values as facts for use in playbooks

- name: Get ArgoCD service IP
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: argocd-server
    namespace: "{{argocd_namespace}}"
  become_user: "{{admin_user}}"
  register: L_ARGOCD_SERVICE_INFO

- name: Export variables
  set_fact:
    ARGOCD_SERVICE_INFO: "{{L_ARGOCD_SERVICE_INFO}}"
    ARGOCD_ADMIN_PASSWROD: "{{argocd_admin_password}}"
