---
- name: Install pip packages
  pip:
    name:
      - kubernetes

- name: Install localhost.direct ssl certificates
  copỳ:
    src: "{{item}}"
    dest: /usr/share/ca-certificates/localhost/
    mode: 0644
  with_items:
  - localhost.direct.crt
  - localhost.direct.key

- name: Transfer argocd server config values file
  template:
    src: values.yml
    dest: "/tmp/argocd_values.yml"
    mode: 0644

- name: Install argocd helm chart
  kubernetes.core.helm:
    release_name: "{{argocd_app_name}}"
    chart_ref: argo-cd
    chart_repo_url: https://argoproj.github.io/argo-helm
    release_namespace: "{{argocd_namespace}}"
    create_namespace: true
    wait: yes
    values_files:
      - /tmp/argocd_values.yml
  become_user: "{{admin_user}}"

###################################################################################
# ArgoCD Auto Updater
- name: Download argocd auto updater manifest
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/stable/manifests/install.yaml
    dest: /tmp/argocd-autoupdater.yaml
    mode: '0664'
    validate_certs: no

- name: Install argocd auto updater
  kubernetes.core.k8s:
    namespace: "{{argocd_namespace}}"
    state: present
    src: /tmp/argocd-autoupdater.yaml
  become_user: "{{admin_user}}"

###################################################################################
# Notification templates and catalog
- name: Download notification templates and catalog
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/notifications_catalog/install.yaml
    dest: /tmp/notifications_catalog.yaml
    mode: '0664'
    validate_certs: no

- name: Install argocd auto updater
  kubernetes.core.k8s:
    namespace: "{{argocd_namespace}}"
    state: present
    src: /tmp/notifications_catalog.yaml
  become_user: "{{admin_user}}"
