# Ref: https://github.com/argoproj/argo-helm/blob/main/charts/argocd-image-updater/values.yaml
extraEnv:
  - name: AWS_DEFAULT_REGION
    value: "eu-west-1"
  - name: AWS_ACCESS_KEY_ID
    value: "{{aws_access_key_id}}"
  - name: AWS_SECRET_ACCESS_KEY
    value: "{{aws_secret_access_key}}"
config:
  gitCommitUser: "ArgoCD Image Updater"
  gitCommitMail: "argocd@golili.net"
  gitCommitTemplate: ""
  registries:
    - name: ECR
      api_url: https://798080816178.dkr.ecr.eu-west-1.amazonaws.com
      prefix: 798080816178.dkr.ecr.eu-west-1.amazonaws.com
      ping: yes
      insecure: no
      credentials: ext:/scripts/auth1.sh
      credsexpire: 10h
# whether to mount authentication scripts, if enabled, the authentication scripts will be mounted on /scripts that can be used to authenticate with registries (ECR)
# refer to https://argocd-image-updater.readthedocs.io/en/stable/configuration/registries/#specifying-credentials-for-accessing-container-registries for more info
authScripts:
  # -- Whether to mount the defined scripts that can be used to authenticate with a registry, the scripts will be mounted at `/scripts`
  enabled: true
  # -- Map of key-value pairs where the key consists of the name of the script and the value the contents
  scripts:
    ecr-login.sh: |   # notice script name matches above
      #!/bin/sh
      aws ecr --region $AWS_DEFAULT_REGION get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d
