dashboard:
  enabled: true
  service:
    type: NodePort
    # -- Service port name
    portName: dashboard
    # -- Service port
    port: 3100
    # -- Service target port
    targetPort: 3100
    # -- (int) Service nodePort
    nodePort: 30100
