# Custom config values, see https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml for reference
controller:
  args:
    appResyncPeriod: "30"
dex:
  enabled: true
server:
  service:
    type: NodePort
    nodePortHttp: {{argocd_node_port}}
  config:
    url: "https://localhost:8081"
    dex.config: |
      connectors:
      - type: ldap
        id: ad
        name: Active Directory
        config:
          host: da04.elconfidencial.int
          insecureNoSSL: true
          insecureSkipVerify: true
          bindDN: CN=go-server,CN=Users,DC=ELCONFIDENCIAL,DC=INT
          bindPW: CN=go-server,CN=Users,DC=ELCONFIDENCIAL,DC=INT
          usernamePrompt: Username
          userSearch:
            baseDN: OU=Tecnico,OU=Usuarios,DC=ELCONFIDENCIAL,DC=INT
            username: sAMAccountName
            idAttr: distinguishedName
            emailAttr: mail
            nameAttr: displayName
          groupSearch:
            baseDN: OU=Grupos,DC=elconfidencial,DC=int
            userMatchers:
            - userAttr: distinguishedName
              groupAttr: member
            nameAttr: name
  rbacConfig:
    policy.csv: |
      p, role:org-admin, applications, *, */*, allow
      p, role:org-admin, clusters, get, *, allow
      p, role:org-admin, repositories, get, *, allow
      p, role:org-admin, repositories, create, *, allow
      p, role:org-admin, repositories, update, *, allow
      p, role:org-admin, repositories, delete, *, allow
      p, role:org-admin, logs, get, *, allow
      p, role:org-admin, exec, create, */*, allow
      g, ldap:administrators, role:org-admin
      p, role:developers, applications, create, demo/*, allow
      p, role:developers, applications, delete, demo/*, allow
      p, role:developers, applications, get, demo/*, allow
      p, role:developers, applications, override, demo/*, allow
      p, role:developers, applications, sync, demo/*, allow
      p, role:developers, applications, update, demo/*, allow
      p, role:developers, logs, get, demo/*, allow
      p, role:developers, exec, create, demo/*, allow
      p, role:developers, projects, get, demo, allow
      g, ldap:developers, role:developers
configs:
  secret:
    argocdServerAdminPassword: "{{argocd_admin_password | password_hash('blowfish')}}"
