# Custom config values, see https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml for reference
controller:
  args:
    appResyncPeriod: "5"
configs:
  cm:
    url: "https://localhost:8081"
server:
  service:
    type: NodePort
    nodePortHttp: {{argocd_node_port}}
