# Custom config values, see https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml for reference
controller:
  args:
    appResyncPeriod: "30"
dex:
  enabled: true
server:
  service:
    type: NodePort
    nodePortHttp: {{argocd_node_port}}
configs:
  secret:
    argocdServerAdminPassword: "{{argocd_admin_password | password_hash('blowfish')}}"
