# Custom config values, see https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml for reference
controller:
  args:
    appResyncPeriod: "30"

server:
  service:
    type: NodePort
    nodePortHttp: {{argocd_node_port}}
#  additionalApplications:
#  - name: rootapp
#    namespace: {{argocd_namespace}}
#    finalizers:
#    - resources-finalizer.argocd.argoproj.io
#    project: default
#    source:
#      repoURL: https://bitbucket.org/capitanhws/rootcd.git
#      targetRevision: HEAD
#      path: apps/
#      directory:
#        recurse: true
#    destination:
#      server: https://kubernetes.default.svc
#      namespace: argocd
#    syncPolicy:
#      automated:
#        prune: false
#        selfHeal: false
#  additionalProjects:
#  - name: development
#    description: Development Environment
#    sourceRepos:
#    - '*'
#    destinations:
#    - namespace: '*'
#      server: '*'
#    clusterResourceWhitelist:
#    - group: '*'
#      kind: '*'
#    namespaceResourceWhitelist:
#    - group: '*'
#      kind: '*'
#  - name: staging
#    description: Staging Environment
#    sourceRepos:
#    - '*'
#    destinations:
#    - namespace: '*'
#      server: '*'
#    clusterResourceWhitelist:
#    - group: '*'
#      kind: '*'
#    namespaceResourceWhitelist:
#    - group: '*'
#      kind: '*'
#  - name: production
#    description: Production Environment
#    sourceRepos:
#    - '*'
#    destinations:
#    - namespace: '*'
#      server: '*'
#    clusterResourceWhitelist:
#    - group: '*'
#      kind: '*'
#    namespaceResourceWhitelist:
#    - group: '*'
#      kind: '*'

configs:
#  credentialTemplates:
#    bitbucket-creds:
#      url: https://bitbucket.org/capitanhws
#      username: luis_novo
#      password: {{vault_bitbucket_password}}
  secret:
    argocdServerAdminPassword: "{{argocd_admin_password | password_hash('blowfish')}}"
