# Custom config values, see https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml for reference
controller:
  args:
    appResyncPeriod: "5"
dex:
  enabled: true
server:
  service:
    type: NodePort
    nodePortHttp: {{argocd_node_port}}
configs:
  cm:
    url: "https://localhost:8081"
    admin.enabled: true
  params:
    secret:
      argocdServerAdminPassword: "{{argocd_admin_password | password_hash('blowfish',ident='2a')}}"
      #argocdServerAdminPassword: "$2a$10$hJA2B9Z587M9ozhig9suYOgaKhog77W9rXsmjr0tdbuaEzyvTCEpW"
