# Ref: https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/values.yaml
controller:
  workflowNamespaces:
    - {{argocd_namespace}}
server:
  authModes:
    - server
  ingress:
    enabled: true
    ingressClassName: public
    hosts:
      - {{argoworkflows_host}}
